import Head from 'next/head';
import styles from '@/modules/contribute/contribute.module.css';
import { Logo, LogoType } from '@/components/logo';
import { GooglePlayButton } from '@/components/googlePlayButton';
import { Card } from '@/components/card';
import { Footer } from '@/components/footer';
import clsx from 'clsx';
import { LangSwitcher } from '@/components/langSwitcher';
import useLocale, { LocalesMap } from '@/utils/useLocale';
import { useRouter } from 'next/router';
import DonateToFunsCard from '@/modules/contribute/donateToFundsCard';
import HelpUkraineCard from '@/modules/contribute/helpUkraineCard';
import Link from 'next/link';

const locales: LocalesMap = {
  ru: {
    title: 'Гречка - Вклад',
    appName: 'Гречка',
    description:
      '— хобби проект и я не планирую на нём зарабатывать. У меня есть работа и постоянный заработок. Если вы очень хотите помочь, то вот несколько вариантов, что вы можете сделать. Спасибо',
    tellFriendsTitle: 'Расскажите друзьям о приложении',
    tellFriendsDescription:
      'Я очень люблю когда мой проекты приносят пользу. Я был бы очень рад если вы рассказали об этом приложении друзьям',
  },
  en: {
    title: 'Buckwheat - Contribute',
    appName: 'Buckwheat',
    description:
      'is a hobby project and I do not plan to make money on it. I have a job and a steady income. If you really want to help, then here are a few things you can do. Thank you',
    tellFriendsTitle: 'Tell your friends about the application',
    tellFriendsDescription:
      'I really love when my projects are useful. I would be very happy if you told your friends about this application',
  },
};

export default function ContributePage() {
  const router = useRouter();
  const t = useLocale(locales);

  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        <Link href="/">
          <Logo className={styles.logo} variant={LogoType.Full} />
        </Link>
        <GooglePlayButton className={styles.googlePlayButton} />
        <div className={styles.langSwitcher}>
          <LangSwitcher />
        </div>
      </header>
      <main className={styles.main}>
        <p className={styles.description}>
          <b className={styles.bold}>{t('appName')}</b> {t('description')}
        </p>
        <div className={styles.cardsRow}>
          {router.locale !== 'ru' && <HelpUkraineCard />}
          {router.locale === 'ru' && <DonateToFunsCard />}
          <Card
            className={clsx(styles.card, styles.tellFriendsCard)}
            title={t('tellFriendsTitle')}
            subtitle={t('tellFriendsDescription')}
          />
        </div>
      </main>
      <Footer />
    </>
  );
}
