import Head from 'next/head';
import Image from 'next/image';
import styles from '@/modules/contribute/contribute.module.css';
import { Logo, LogoType } from '@/components/logo';
import { GooglePlayButton } from '@/components/googlePlayButton';
import { Card } from '@/components/card';
import { Footer } from '@/components/footer';
import clsx from 'clsx';
import { LangSwitcher } from '@/components/langSwitcher';
import useLocale, { LocalesMap } from '@/utils/useLocale';
import { useRouter } from 'next/router';
import DonateToFunsCard from '@/modules/contribute/donateToFundsCard';
import HelpUkraineCard from '@/modules/contribute/helpUkraineCard';
import Link from 'next/link';

const locales: LocalesMap = {
  ru: {
    title: 'Гречка - Вклад',
    description:
      'Гречка это хобби-проект и я не планирую на этом зарабатывать, но если вы хотите помочь, то вот несколько способов как это сделать',
    tellFriendsTitle: 'Расскажите друзьям о приложении',
    tellFriendsDescription:
      'Очень приятно осознавать, что много людей пользуются вашим продуктом. Это делает меня счастливым',
  },
  en: {
    title: 'Buckwheat - Contribute',
    description:
      'Buckwheat is a hobby project and I do not plan to earn money on it, but if you want to help, here are a few ways how to do it',
    tellFriendsTitle: 'Tell your friends about the application',
    tellFriendsDescription:
      'It is very nice to realize that many people use your product. It makes me happy',
  },
};

export default function ContributePage() {
  const router = useRouter();
  const t = useLocale(locales);

  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        <Link href="/">
          <Logo className={styles.logo} variant={LogoType.Full} />
        </Link>
        <GooglePlayButton className={styles.googlePlayButton} />
        <div className={styles.langSwitcher}>
          <LangSwitcher />
        </div>
      </header>
      <main className={styles.main}>
        <p className={styles.description}>{t('description')}</p>
        <div className={styles.cardsRow}>
          {router.locale !== 'ru' && <HelpUkraineCard />}
          {router.locale === 'ru' && <DonateToFunsCard />}
          <Card
            className={clsx(styles.card, styles.tellFriendsCard)}
            title={t('tellFriendsTitle')}
            subtitle={t('tellFriendsDescription')}
          />
        </div>
      </main>
      <Footer />
    </>
  );
}
