import Head from 'next/head';
import Image from 'next/image';
import styles from '@/modules/home/home.module.css';
import { Logo, LogoType } from '@/components/logo';
import { GooglePlayButton } from '@/components/googlePlayButton';
import { Card } from '@/components/card';
import { Footer } from '@/components/footer';
import clsx from 'clsx';
import phoneMockupImage from '@/assets/images/phone-mockup-1.png';
import screenshotMainImage from '@/assets/images/screenshot-main.png';
import { LangSwitcher } from '@/components/langSwitcher';
import useLocale, { LocalesMap } from '@/utils/useLocale';

const locales: LocalesMap = {
  ru: {
    title: 'Гречка',
    slogan: 'Приложение, которое поможет вам тратить деньги с умом',
    description:
      'Записывая каждую трату, вы отрезвляете разум и даете представление о том, сколько и как вы можете потратить.',
    howWorkTitle: 'Как это работает?',
    howWorkDescription:
      'Записывая каждую трату, вы отрезвляете разум и даете представление о том, сколько и как вы можете потратить.',
    somethingElseTitle: 'Что-то еще?',
    somethingElseDescription:
      'Нет, это все. Все очень просто. Гречиха — это самое простое приложение, которое, как известно, может вам помочь',
    contributeTitle: 'Вклад',
    contributeDescription: 'Узнайте, как вы можете помочь проекту',
  },
  en: {
    title: 'Buckwheat',
    slogan: 'App that helps you spend money wisely',
    description:
      'Writing down each spending sobers the mind and gives you an idea of how much and how you can spend.',
    howWorkTitle: 'How its work?',
    howWorkDescription:
      'Writing down each spending sobers the mind and gives you an idea of how much and how you can spend',
    somethingElseTitle: 'Something else?',
    somethingElseDescription:
      'No, it `s all. Everything is very simple. Buckwheat is the simplest application recognized to help you',
    contributeTitle: 'Contribute',
    contributeDescription: 'Find out how you can help the project',
  },
};

export default function Home() {
  const t = useLocale(locales);

  return (
    <>
      <Head>
        <title>{t('title')}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <header className={styles.header}>
        <div className={styles.langSwitcher}>
          <LangSwitcher />
        </div>
        <Logo className={styles.logo} variant={LogoType.Full} />
        <h1>{t('slogan')}</h1>
        <p>{t('description')}</p>
        <GooglePlayButton className={styles.googlePlayButton} />
      </header>
      <main className={styles.main}>
        <Card
          className={styles.howItsWorkCard}
          title={t('howWorkTitle')}
          subtitle={t('howWorkDescription')}
        >
          <div className={styles.mockupPhoneContiner}>
            <Image
              className={styles.screenshotMain}
              height={2340}
              width={1080}
              alt=""
              src={screenshotMainImage}
            />
            <Image
              className={styles.mockupPhone}
              height={900}
              width={1050}
              alt=""
              src={phoneMockupImage}
            />
          </div>
        </Card>
        <div className={styles.cardsRow}>
          <Card
            className={clsx(styles.card, styles.somethingElseCard)}
            title={t('howWorkDescription')}
            subtitle={t('somethingElseDescription')}
          />
          <Card
            className={clsx(styles.card, styles.contributeCard)}
            title={t('contributeTitle')}
            subtitle={t('contributeDescription')}
          />
        </div>
      </main>
      <Footer />
    </>
  );
}

/* export const getStaticPaths = () => {
  return {
    paths: [{ locale: 'en-US' }, { locale: 'ru' }],
    fallback: false,
  };
}; */
